# Generated by Django 5.2.3 on 2025-06-19 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="Annonymous_Doctor",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True,
                        default="incoming@codices-divinum.com",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        default="The_Great_Gaa_Hospital",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "speciality",
                    models.CharField(
                        blank=True,
                        default="General Practitioner",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "doctors",
                    models.ManyToManyField(
                        blank=True, related_name="patient", to="datavault.doctorprofile"
                    ),
                ),
            ],
        ),
    ]
