# Generated by Django 5.2.3 on 2025-06-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datavault", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="patient_details",
            field=models.TextField(
                blank=True, default="No Details from Patient is Given", null=True
            ),
        ),
    ]
